local _, NS = ...

NS.Locales.frFR = {
    ADDON_NAME = "NextStep",
    TAGLINE = "Sachez ce qui compte pour la suite.",
    WHAT_MATTERS_NEXT = "CE QUI COMPTE MAINTENANT",
    SUMMARY = "RÉSUMÉ",
    REFRESH = "Actualiser",
    SETTINGS = "Paramètres",
    WHY_PREFIX = "Pourquoi : ",
    FALLBACK = "Vous êtes à jour sur les priorités que NextStep peut actuellement détecter.",
    LEVELING_TITLE = "Continuez à progresser",
    LEVELING_DESCRIPTION = "Poursuivez votre série de quêtes actuelle jusqu’au niveau maximum.",
    LEVELING_REASON = "La plupart des systèmes de progression de haut niveau deviennent pertinents au niveau maximum.",
    TRACKED_QUEST_TITLE = "Continuez : %s",
    TRACKED_QUEST_DESCRIPTION = "Terminez la quête vers laquelle le jeu vous guide actuellement.",
    TRACKED_STORY_DESCRIPTION = "Poursuivez la quête d’histoire vers laquelle le jeu vous guide actuellement.",
    TRACKED_QUEST_REASON = "Elle fait directement progresser votre parcours de montée en niveau.",
    QUEST_TURN_IN_TITLE = "Rendez vos quêtes terminées",
    QUEST_TURN_IN_DESCRIPTION = "%d %s à rendre pour %s EXP.",
    QUEST_TURN_IN_REASON = "Les objectifs sont terminés. Cette expérience est disponible dès que vous rendez les quêtes.",
    RESTED_XP_TITLE = "Utilisez votre expérience reposée",
    RESTED_XP_DESCRIPTION = "%s points d’EXP reposée sont disponibles, soit environ %d %% d’un niveau.",
    RESTED_XP_REASON = "L’expérience reposée augmente l’expérience gagnée sur les ennemis éligibles.",
    LEVELING_DUNGEON_TITLE = "Faites un donjon pour gagner de l’EXP et de l’équipement",
    LEVELING_DUNGEON_DESCRIPTION = "Le client indique %d %s pour le niveau actuel de votre personnage.",
    LEVELING_DUNGEON_REASON = "Les donjons donnent de l’expérience et leurs boss peuvent fournir de l’équipement adapté à votre niveau.",
    EMPTY_GEAR_TITLE = "Remplissez vos emplacements d’équipement vides",
    EMPTY_GEAR_LEVELING_DESCRIPTION = "Équipez les emplacements suivants : %s. Les quêtes et les donjons de progression peuvent les remplir.",
    EMPTY_GEAR_MAX_DESCRIPTION = "Équipez les emplacements suivants : %s. Les donjons, raids, objets fabriqués ou récompenses hebdomadaires actuels peuvent les remplir.",
    EMPTY_GEAR_REASON = "Remplir un emplacement d’équipement de combat augmente de façon certaine la puissance du personnage.",
    VAULT_CLAIM_TITLE = "Récupérez votre récompense de la grande chambre forte",
    VAULT_CLAIM_DESCRIPTION = "Une récompense hebdomadaire est prête à être récupérée.",
    VAULT_CLAIM_REASON = "Vous récupérez ainsi un choix de récompense hebdomadaire déjà gagné.",
    VAULT_UNLOCK_TITLE = "Prochaine option de la chambre forte : %s",
    VAULT_UNLOCK_REASON = "Chaque palier terminé ajoute un choix de récompense hebdomadaire.",
    VAULT_ROUTE_DUNGEON = "Terminez encore %d %s éligibles.",
    VAULT_ROUTE_RAID = "Vainquez encore %d %s éligibles.",
    VAULT_ROUTE_PROGRESS = "Gagnez encore %d points de progression de la chambre forte via %s.",
    VAULT_ROUTE_FOLLOWING = " L’option suivante demande ensuite ce supplément : %d %s.",
    VAULT_TYPE_DUNGEON = "donjon",
    VAULT_TYPE_RAID = "rencontre de raid",
    VAULT_TYPE_PVP = "objectif JcJ coté",
    VAULT_TYPE_WORLD = "activité en extérieur",
    VAULT_TYPE_CONCESSION = "activité",
    VAULT_TYPE_UNKNOWN = "activité",
    VAULT_CATEGORY_LABELS = {
        dungeon = "Donjons",
        raid = "Raid",
        pvp = "JcJ coté",
        world = "Activités en extérieur",
        concession = "Activités",
        unknown = "Activités",
    },
    VAULT_PROGRESS_SOURCES = {
        pvp = "le JcJ coté",
        world = "les activités en extérieur",
        other = "les activités éligibles",
    },
    VAULT_UNAVAILABLE = "Données de la chambre forte indisponibles",
    NO_CURRENCY = "Aucune monnaie suivie configurée",
    SPECIALIZATION_UNAVAILABLE = "Spécialisation indisponible",
    UNAVAILABLE = "Indisponible",
    ALL_CLEAR = "Rien de prioritaire pour le moment",
    SETTINGS_TITLE = "Paramètres de NextStep",
    SHOW_OPTIONAL = "Afficher les recommandations facultatives",
    LOCK_WINDOW = "Verrouiller la fenêtre",
    REMEMBER_POSITION = "Mémoriser la position de la fenêtre",
    MAX_RECOMMENDATIONS = "Nombre maximal de recommandations : %d",
    CHARACTER_UNAVAILABLE = "Personnage indisponible",
    LEVEL_FORMAT = "Niveau %d",
    XP_PROGRESS_FORMAT = " (%.1f %% EXP)",
    EQUIPPED_FORMAT = "Équipé %s",
    AVERAGE_FORMAT = "Moyenne %s",
    VAULT_SUMMARY = "Chambre forte %d/%d",
    CURRENCY_FALLBACK = "Monnaie",
    LIST_AND_MORE = ", et %d de plus",
    DEBUG_MODE_ENABLED = "Mode débogage activé.",
    DEBUG_MODE_DISABLED = "Mode débogage désactivé.",
    DEBUG_STATE_DEFERRED = "Actualisation reportée après le combat. Affichage de l’état en cache.",
    DEBUG_RECOMMENDATIONS_DEFERRED = "Actualisation reportée après le combat. Affichage des recommandations en cache.",
    SETTINGS_RESET = "Paramètres réinitialisés.",
    COMMANDS_HELP = "Commandes : /nextstep, /ns, /ns debug, /ns debug state, /ns debug recommendations, /ns reset",
    DEBUG_STATE_TITLE = "État du personnage NextStep",
    DEBUG_RECOMMENDATIONS_TITLE = "Recommandations NextStep",
    DEBUG_RULE_TRACE = "TRACE DES RÈGLES",
    DEBUG_RECOMMENDATIONS = "RECOMMANDATIONS",
    DEBUG_RULE_FORMAT = "%s | déclenchée=%s | invalides=%d",
    DEBUG_ERROR_FORMAT = "  erreur : %s",
    DEBUG_RECOMMENDATION_ID_FORMAT = "  recommandation : %s",
    DEBUG_RECOMMENDATION_FORMAT = "%s | règle=%s | priorité=%s | importance=%s\n  raison : %s",
    UNKNOWN = "inconnu",
    API_CALL_FAILED = "Échec de l’appel API : %s",
    IMPORTANCE_LABELS = {
        CRITICAL = "CRITIQUE",
        HIGH = "HAUTE VALEUR",
        USEFUL = "UTILE",
        OPTIONAL = "FACULTATIF",
        COMPLETED = "TERMINÉ",
    },
    NOUNS = {
        quest = { one = "quête", other = "quêtes" },
        dungeon = { one = "donjon", other = "donjons" },
        boss = { one = "boss", other = "boss" },
        raidBoss = { one = "boss de raid", other = "boss de raid" },
        vaultProgress = { one = "point de progression de la chambre forte", other = "points de progression de la chambre forte" },
    },
    VAULT_ACTIVITY_NAMES = {
        dungeon = "Progression des donjons de la grande chambre forte",
        raid = "Progression des raids de la grande chambre forte",
        pvp = "Progression JcJ coté de la grande chambre forte",
        world = "Progression en extérieur de la grande chambre forte",
        concession = "Progression des activités de la grande chambre forte",
        unknown = "Progression de la grande chambre forte",
    },
    SLOT_NAMES = {
        head = "Tête",
        neck = "Cou",
        shoulder = "Épaules",
        chest = "Torse",
        waist = "Taille",
        legs = "Jambes",
        feet = "Pieds",
        wrist = "Poignets",
        hands = "Mains",
        finger1 = "Doigt 1",
        finger2 = "Doigt 2",
        trinket1 = "Bijou 1",
        trinket2 = "Bijou 2",
        back = "Dos",
        mainHand = "Main principale",
    },
}
