local _, NS = ...

NS.Locales = NS.Locales or {}
NS.Locales.enUS = {
    ADDON_NAME = "NextStep",
    TAGLINE = "Know what matters for you next.",
    WHAT_MATTERS_NEXT = "WHAT MATTERS NEXT",
    SUMMARY = "SUMMARY",
    REFRESH = "Refresh",
    SETTINGS = "Settings",
    WHY_PREFIX = "Why: ",
    FALLBACK = "You're caught up on the high-priority progression NextStep can currently detect.",
    FALLBACK_SELECTED_GOALS = "NextStep has no verified recommendation for this character's selected goals yet.",
    LEVELING_TITLE = "Continue leveling",
    LEVELING_DESCRIPTION = "Continue your current quest path toward maximum level.",
    LEVELING_REASON = "Most endgame progression systems become relevant at maximum level.",
    TRACKED_QUEST_TITLE = "Continue: %s",
    TRACKED_QUEST_DESCRIPTION = "Finish the quest the game is currently guiding you toward.",
    TRACKED_STORY_DESCRIPTION = "Continue the story quest the game is currently guiding you toward.",
    TRACKED_QUEST_REASON = "This directly advances your active leveling path.",
    QUEST_TURN_IN_TITLE = "Turn in completed quests",
    QUEST_TURN_IN_DESCRIPTION = "%d completed %s ready for %s XP.",
    QUEST_TURN_IN_REASON = "The objectives are complete, so this experience is immediately available when you turn them in.",
    RESTED_XP_TITLE = "Use your rested experience",
    RESTED_XP_DESCRIPTION = "%s rested XP is available, about %d%% of a level.",
    RESTED_XP_REASON = "Rested XP increases experience from eligible enemy kills.",
    LEVELING_DUNGEON_TITLE = "Use a leveling dungeon for XP and gear",
    LEVELING_DUNGEON_DESCRIPTION = "The client reports %d level-appropriate %s for your character.",
    LEVELING_DUNGEON_REASON = "Dungeons provide experience, and bosses can drop level-appropriate equipment.",
    EMPTY_GEAR_TITLE = "Fill your empty equipment slots",
    EMPTY_GEAR_LEVELING_DESCRIPTION = "Equip items in: %s. Quest rewards and leveling dungeons can fill these slots.",
    EMPTY_GEAR_MAX_DESCRIPTION = "Equip items in: %s. Current dungeons, raids, crafted gear, or weekly rewards can fill these slots.",
    EMPTY_GEAR_REASON = "A filled combat equipment slot is a reliable character power gain.",
    VAULT_CLAIM_TITLE = "Claim your Great Vault reward",
    VAULT_CLAIM_DESCRIPTION = "A weekly reward is ready to claim.",
    VAULT_CLAIM_REASON = "Claiming it gives you an earned weekly reward choice.",
    VAULT_UNLOCK_TITLE = "Next Vault option: %s",
    VAULT_UNLOCK_REASON = "Each completed threshold adds another weekly reward choice.",
    VAULT_ROUTE_DUNGEON = "Complete %d more qualifying %s.",
    VAULT_ROUTE_RAID = "Defeat %d more qualifying raid %s.",
    VAULT_ROUTE_PROGRESS = "Earn %d more Vault progress through %s.",
    VAULT_ROUTE_FOLLOWING = " The following option needs %d additional %s after that.",
    VAULT_TYPE_DUNGEON = "dungeon",
    VAULT_TYPE_RAID = "raid encounter",
    VAULT_TYPE_PVP = "rated PvP objective",
    VAULT_TYPE_WORLD = "world activity",
    VAULT_TYPE_CONCESSION = "activity",
    VAULT_TYPE_UNKNOWN = "activity",
    VAULT_CATEGORY_LABELS = {
        dungeon = "Dungeons",
        raid = "Raid",
        pvp = "Rated PvP",
        world = "World activities",
        concession = "Activities",
        unknown = "Activities",
    },
    VAULT_PROGRESS_SOURCES = {
        pvp = "rated PvP",
        world = "world activities",
        other = "qualifying activities",
    },
    VAULT_UNAVAILABLE = "Vault data unavailable",
    NO_CURRENCY = "No tracked currency configured",
    SPECIALIZATION_UNAVAILABLE = "Specialization unavailable",
    UNAVAILABLE = "Unavailable",
    ALL_CLEAR = "All clear for now",
    SETTINGS_TITLE = "NextStep Settings",
    SHOW_OPTIONAL = "Show optional recommendations",
    SHOW_NEXT_STEP_WIDGET = "Show compact next step window",
    LOCK_WINDOW = "Lock NextStep windows",
    REMEMBER_POSITION = "Remember main window position",
    MAX_RECOMMENDATIONS = "Maximum recommendations: %d",
    CHARACTER_UNAVAILABLE = "Character unavailable",
    LEVEL_FORMAT = "Level %d",
    XP_PROGRESS_FORMAT = " (%.1f%% XP)",
    EQUIPPED_FORMAT = "Equipped %s",
    AVERAGE_FORMAT = "Average %s",
    VAULT_SUMMARY = "Vault %d/%d",
    CURRENCY_FALLBACK = "Currency",
    LIST_AND_MORE = ", and %d more",
    DEBUG_MODE_ENABLED = "Debug mode enabled.",
    DEBUG_MODE_DISABLED = "Debug mode disabled.",
    DEBUG_STATE_DEFERRED = "Refresh deferred until combat ends. Showing cached state.",
    DEBUG_RECOMMENDATIONS_DEFERRED = "Refresh deferred until combat ends. Showing cached recommendations.",
    SETTINGS_RESET = "Settings and current character goals reset.",
    EDIT_CHARACTER_GOALS = "Edit character goals",
    ONBOARDING_TITLE = "Welcome to NextStep",
    ONBOARDING_INTRODUCTION = "Choose what NextStep should prioritize for %s. Critical earned rewards may still appear.",
    ONBOARDING_GOALS = "WHAT MATTERS FOR THIS CHARACTER?",
    ONBOARDING_SHOW_WIDGET = "Show a compact next step window after login",
    ONBOARDING_SAVE = "Save and start",
    ONBOARDING_GOAL_REQUIRED = "Select at least one goal.",
    WIDGET_HEADING = "NEXT STEP",
    WIDGET_DISABLED_MESSAGE = "The compact window is disabled. Use /nextstep to open your plan.",
    COMMANDS_HELP = "Commands: /nextstep, /ns, /ns tutorial, /ns debug, /ns debug state, /ns debug recommendations, /ns reset",
    DEBUG_STATE_TITLE = "NextStep PlayerState",
    DEBUG_RECOMMENDATIONS_TITLE = "NextStep Recommendations",
    DEBUG_RULE_TRACE = "RULE TRACE",
    DEBUG_RECOMMENDATIONS = "RECOMMENDATIONS",
    DEBUG_RULE_FORMAT = "%s | fired=%s | invalid=%d",
    DEBUG_ERROR_FORMAT = "  error: %s",
    DEBUG_RECOMMENDATION_ID_FORMAT = "  recommendation: %s",
    DEBUG_RECOMMENDATION_FORMAT = "%s | rule=%s | priority=%s | importance=%s\n  reason: %s",
    UNKNOWN = "unknown",
    API_CALL_FAILED = "API call failed: %s",
    GOAL_LABELS = {
        experience = "Level faster",
        gear = "Increase item level",
        mounts = "Collect mounts",
        pets = "Collect battle pets",
    },
    GOAL_DESCRIPTIONS = {
        experience = "Prioritize verified quest, rested XP, and leveling dungeon progress.",
        gear = "Prioritize verified equipment and weekly reward opportunities.",
        mounts = "Prioritize verified mount requirements and acquisition paths when available.",
        pets = "Prioritize verified battle pet requirements and acquisition paths when available.",
    },
    IMPORTANCE_LABELS = {
        CRITICAL = "CRITICAL",
        HIGH = "HIGH VALUE",
        USEFUL = "USEFUL",
        OPTIONAL = "OPTIONAL",
        COMPLETED = "COMPLETED",
    },
    NOUNS = {
        quest = { one = "quest", other = "quests" },
        dungeon = { one = "dungeon", other = "dungeons" },
        boss = { one = "boss", other = "bosses" },
        raidBoss = { one = "raid boss", other = "raid bosses" },
        vaultProgress = { one = "Vault progress", other = "Vault progress" },
    },
    VAULT_ACTIVITY_NAMES = {
        dungeon = "Great Vault dungeon progress",
        raid = "Great Vault raid progress",
        pvp = "Great Vault rated PvP progress",
        world = "Great Vault world progress",
        concession = "Great Vault activity progress",
        unknown = "Great Vault progress",
    },
    SLOT_NAMES = {
        head = "Head",
        neck = "Neck",
        shoulder = "Shoulders",
        chest = "Chest",
        waist = "Waist",
        legs = "Legs",
        feet = "Feet",
        wrist = "Wrists",
        hands = "Hands",
        finger1 = "Finger 1",
        finger2 = "Finger 2",
        trinket1 = "Trinket 1",
        trinket2 = "Trinket 2",
        back = "Back",
        mainHand = "Main hand",
    },
}
