local _, NS = ...

NS.Recommendation = NS.Recommendation or {}
local Reasons = {}
NS.Recommendation.Reasons = Reasons

Reasons.LEVELING = NS.L.LEVELING_REASON
Reasons.TRACKED_QUEST = NS.L.TRACKED_QUEST_REASON
Reasons.QUEST_TURN_IN = NS.L.QUEST_TURN_IN_REASON
Reasons.RESTED_XP = NS.L.RESTED_XP_REASON
Reasons.LEVELING_DUNGEON = NS.L.LEVELING_DUNGEON_REASON
Reasons.EMPTY_GEAR = NS.L.EMPTY_GEAR_REASON
Reasons.VAULT_CLAIM = NS.L.VAULT_CLAIM_REASON
Reasons.VAULT_UNLOCK = NS.L.VAULT_UNLOCK_REASON
